package com.Exception.Handling;

public class CustomExceptionTest {
	  public static void main(String[] args) {
	        try {
	            int num1=10,num2=20;
	           
	            if(num1>num2) {
	                throw new CustomException("Negative difference");
	            }
	        }catch(CustomException e) {
	            System.out.println(e.getMessage());
	        }
	    }
}

